# Generated by Django 4.0.3 on 2022-05-30 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=245, verbose_name='Nombre')),
                ('es_doc', models.BooleanField(default=False, verbose_name='Documento')),
            ],
        ),
    ]
