# Generated by Django 4.0.3 on 2022-03-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estatus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estatus',
            name='activo',
        ),
        migrations.AddField(
            model_name='estatus',
            name='es_doc',
            field=models.BooleanField(default=False, verbose_name='Documento'),
        ),
    ]
