# Generated by Django 4.0.3 on 2022-03-17 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tipo_expediente', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('estatus', '0002_remove_estatus_activo_estatus_es_doc'),
        ('unidad', '0002_alter_unidad_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=30, verbose_name='Identificador')),
                ('nombre', models.CharField(max_length=245, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=245, null=True, verbose_name='Descripción')),
                ('asunto', models.CharField(max_length=245, verbose_name='Asunto')),
                ('fecha_creacion', models.DateTimeField(verbose_name='Creación')),
                ('fecha_cierre', models.DateTimeField(null=True, verbose_name='Cierre')),
                ('ubicacion', models.CharField(max_length=245, verbose_name='Ubicación')),
                ('motivo_rechazo', models.CharField(max_length=245, verbose_name='Nombre')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('estatus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Estatus', to='estatus.estatus')),
                ('tipo_expediente', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Tipo_expediente', to='tipo_expediente.tipoexpediente')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Unidad', to='unidad.unidad')),
                ('usuario_crea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Creador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
