# Generated by Django 4.0.3 on 2022-05-30 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tipo_expediente', '0001_initial'),
        ('usuarios', '0001_initial'),
        ('unidad', '0001_initial'),
        ('estatus', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=30, unique=True, verbose_name='Identificador')),
                ('nombre', models.CharField(max_length=245, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=245, null=True, verbose_name='Descripción')),
                ('asunto', models.CharField(max_length=245, verbose_name='Asunto')),
                ('fecha_creacion', models.DateTimeField(null=True, verbose_name='Creación')),
                ('fecha_cierre', models.DateTimeField(null=True, verbose_name='Cierre')),
                ('ubicacion', models.CharField(max_length=245, verbose_name='Ubicación')),
                ('motivo_rechazo', models.CharField(max_length=245, verbose_name='motivo_rechazo')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('estatus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Estatus', to='estatus.estatus')),
                ('tipo_expediente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Tipo_expediente', to='tipo_expediente.tipoexpediente')),
                ('unidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Unidad', to='unidad.unidad')),
                ('usuario_crea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfiluser')),
            ],
        ),
        migrations.CreateModel(
            name='Registra_actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.CharField(max_length=245, null=True, verbose_name='Hora')),
                ('hora', models.CharField(max_length=245, null=True, verbose_name='Hora')),
                ('rol', models.CharField(max_length=245, null=True, verbose_name='Rol')),
                ('actividad', models.CharField(max_length=245, verbose_name='Actividad')),
                ('detalle_objeto', models.CharField(max_length=245, null=True, verbose_name='Detalle_objeto')),
                ('objeto', models.CharField(max_length=245, verbose_name='Destino')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Usuario', to='usuarios.perfiluser')),
            ],
        ),
        migrations.CreateModel(
            name='Expediente_aprobador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_rechazo', models.CharField(max_length=245, null=True, verbose_name='motivo_rechazo')),
                ('id_estatus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_Estatus', to='estatus.estatus')),
                ('id_expediente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Expediente', to='expediente.expediente')),
                ('id_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Usuario_realiza', to='usuarios.perfiluser')),
            ],
        ),
    ]
