# Generated by Django 4.0.3 on 2022-09-12 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_perfiluser_transferido'),
        ('expediente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expediente_deputy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deputy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Deputy', to='usuarios.perfiluser')),
                ('expediente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Exp', to='expediente.expediente')),
                ('usuario_crea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Usuario_crea', to='usuarios.perfiluser')),
            ],
        ),
    ]
