# Generated by Django 4.0.3 on 2022-09-29 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_perfiluser_deputy'),
        ('expediente', '0002_expediente_deputy'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='usuario_anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Usuario_anterior', to='usuarios.perfiluser'),
        ),
        migrations.CreateModel(
            name='Expediente_transferido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('expediente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Expdiente_en_cuestion', to='expediente.expediente')),
                ('usuario_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Usuario_asignado', to='usuarios.perfiluser')),
                ('usuario_crea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Usuario_creador', to='usuarios.perfiluser')),
            ],
        ),
    ]
