# Generated by Django 4.0.3 on 2022-03-17 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0002_alter_expediente_motivo_rechazo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expediente',
            name='usuario_crea',
        ),
    ]
