# Generated by Django 4.0.3 on 2022-10-19 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0003_expediente_usuario_anterior_expediente_transferido'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente_aprobador',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
