# Generated by Django 4.0.3 on 2022-03-17 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tipo_expediente', '0001_initial'),
        ('unidad', '0002_alter_unidad_descripcion'),
        ('expediente', '0004_alter_expediente_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='tipo_expediente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Tipo_expediente', to='tipo_expediente.tipoexpediente'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='unidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Unidad', to='unidad.unidad'),
        ),
    ]
