# Generated by Django 4.0.3 on 2022-03-17 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estatus', '0002_remove_estatus_activo_estatus_es_doc'),
        ('expediente', '0005_alter_expediente_tipo_expediente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='estatus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Estatus', to='estatus.estatus'),
        ),
    ]
