# Generated by Django 4.0.3 on 2022-05-30 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=245, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=245, null=True, verbose_name='Descripción')),
            ],
        ),
    ]
