# Generated by Django 4.0.3 on 2022-03-22 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfiluser',
            name='vigente',
        ),
    ]
