# Generated by Django 4.0.3 on 2022-03-22 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unidad', '0003_unidad_jefe_unidad'),
        ('usuarios', '0002_remove_perfiluser_vigente'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfiluser',
            name='unidad_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Unidad_user', to='unidad.unidad'),
        ),
    ]
