# Generated by Django 4.0.3 on 2022-09-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_perfiluser_transferido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfiluser',
            name='transferido',
            field=models.BooleanField(default=False, verbose_name='Transferido'),
        ),
    ]
