# Generated by Django 4.0.3 on 2022-09-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_perfiluser_transferido'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfiluser',
            name='deputy',
            field=models.BooleanField(default=False, verbose_name='Deputy'),
        ),
    ]
