# Generated by Django 4.0.3 on 2022-10-17 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0004_perfiluser_deputy'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfiluser',
            name='usuario_deputy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_deputy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='perfiluser',
            name='jefe_inmediato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Jefe_inmediato', to=settings.AUTH_USER_MODEL),
        ),
    ]
