# Generated by Django 4.0.3 on 2022-10-21 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_perfiluser_usuario_deputy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfiluser',
            name='es_deputy',
            field=models.BooleanField(default=False, verbose_name='Es_deputy'),
        ),
    ]
