# Generated by Django 4.0.3 on 2022-05-30 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=245, unique=True, verbose_name='Nombre')),
                ('siglas', models.CharField(default='', max_length=3, unique=True, verbose_name='Siglas')),
                ('descripcion', models.CharField(max_length=245, null=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('jefe_unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Jefe_unidad', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
