# Generated by Django 4.0.3 on 2022-03-22 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('unidad', '0002_alter_unidad_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidad',
            name='jefe_unidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Jefe_unidad', to=settings.AUTH_USER_MODEL),
        ),
    ]
