# Generated by Django 4.0.3 on 2022-09-23 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unidad', '0001_initial'),
        ('tipo_expediente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoexpediente',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Unidad_tipo_exp', to='unidad.unidad'),
        ),
        migrations.AlterField(
            model_name='tipoexpediente',
            name='nombre',
            field=models.CharField(max_length=245, verbose_name='Nombre'),
        ),
        migrations.AlterUniqueTogether(
            name='tipoexpediente',
            unique_together={('nombre', 'unidad')},
        ),
    ]
