# Generated by Django 4.0.3 on 2022-03-25 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0008_alter_expediente_usuario_crea'),
        ('metadato', '0002_metadato_tipo_expediente'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadato',
            name='expediente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Tipo_exp', to='expediente.expediente'),
        ),
    ]
